name: TVBOX Check

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Requests
        run: |
          pip install requests

      - name: Run Check
        run: |
          python check.py

      - name: Commit Results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add active.json disabled.json

          git diff --cached --quiet || git commit -m "auto update sources"

          git push
