name: Check Sources

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create active files
        run: |
          cp sources.json active.json
          echo "[]" > disabled.json

      - name: Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "auto update" || exit 0
          git push
